In [41]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from collections import defaultdict
import os
import pickle
import scipy.stats as st

from itertools import combinations
from scipy.stats import chi2

from code.algorithm_alpha import algorithm_alpha
from code.algorithm_t import algorithm_t
from scipy.special import factorial

In [42]:
from code.DataGeneration_class import DataGenerationBernoulli
DGB = DataGenerationBernoulli(ran_var=True, ran_int=True, n_fix=1, sim=True)

DGB.set_parameters()

In [43]:
fix = DGB.fix
lengths = DGB.lengths
y = DGB.y
N = DGB.N
t = DGB.t


In [44]:
N

10

In [46]:
lengths

array([98, 88, 81, 99, 82, 75, 81, 98, 84, 87])

In [47]:
for i in range(3):
    print(i)

0
1
2


In [48]:
np.size(group)

10

In [49]:
np.where(group==3)[0]

array([2])

In [50]:
len(t[0])

98

In [51]:
fix[0][0]

array([-0.6925 , -1.25931, -0.44388, -0.78518, -0.07402, -1.00986,
       -0.63444, -1.54769, -0.04582, -0.43384, -0.13721, -0.06008,
        0.27003, -0.61034,  1.84967, -0.24106, -1.16659,  0.31189,
       -0.23665, -1.79361, -1.03271, -1.4069 , -0.68033,  0.61595,
        0.21921,  0.12528, -0.08035,  0.16584,  0.32398, -0.23588,
        1.48254,  0.27939, -0.86792, -0.35917,  1.85143,  1.51245,
       -0.23358, -1.64082, -0.17552,  1.62883, -1.40108,  0.10277,
        0.46575, -0.23789,  2.64198,  1.94607, -1.3959 , -1.02396,
        0.50049,  1.71414,  2.1385 , -0.70849, -0.52952, -0.28142,
       -0.80258,  0.29272,  0.62138, -0.23744, -0.62085, -0.25382,
       -0.42615,  0.13464, -1.71258, -0.78426, -0.10483, -0.74355,
       -0.96371, -0.23504,  0.03733, -0.86752,  1.65434, -0.27834,
        1.40992, -1.77726,  1.25921,  0.20901, -0.67899, -0.44731,
       -0.30237, -0.70605,  0.25298,  0.27725, -1.3998 ,  1.38106,
        0.65934, -0.62671, -0.80136, -0.99403, -0.78792,  1.04

In [57]:
x = np.array([[1,2,3], [4,5,6]])
x.ndim

2

In [58]:
x = np.array([1,2,3])
x.ndim

1

In [52]:
sim = False

ran_var = True
ran_int = True
n_fix = 1
tol = 0.05  # set as 0.01, 0.05 or 0.10 if algorithm_alpha is used; 
            # otherwise use algorithm_t and tune the tolerance tol
model = 'B' # 'B' for Bernoulli and 'P' for Poisson

# t = df.groupby('CNT')['VARIABLE_NAME'].apply(np.array).values.tolist()

knots, par, W, hess_ran, hess_fix = algorithm_alpha(ran_var, ran_int, n_fix, sim, tol, model, fix, lengths, y, N, t)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/alessandragni/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/lg/0lc2g3rx12jf4ztglsz2bgc80000gn/T/ipykernel_66419/2098056283.py", line 12, in <module>
    knots, par, W, hess_ran, hess_fix = algorithm_alpha(ran_var, ran_int, n_fix, sim, tol, model, fix, lengths, y, N, t)
  File "/Users/alessandragni/Documents/DATA/POLITECNICO/PHD/CODE_REPO/SPGLMM_clustering/code/algorithm_alpha.py", line 220, in algorithm_alpha
    n_params = np.size(AC.knots) + (len(AC.knots) - 1) + len(AC.par)
  File "/Users/alessandragni/Documents/DATA/POLITECNICO/PHD/CODE_REPO/SPGLMM_clustering/code/Auxiliary_functions.py", line 36, in loglikelihood
IndexError: index 3 is out of bounds for axis 0 with size 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alessandragni